### ISSUE TITLE
Getting Exception: Response Code is found : 404 while trying the url : https://corona.lmao.ninja/countries/{Bangladesh}.

### ISSUE THREAD

**Issue by sunjid-rahman** [msghera/corona-data#2]
![image](https://user-images.githubusercontent.com/39432601/77766268-9c0a0200-7069-11ea-9a2f-c93dd05f4d47.png)

**Comment by msghera** [comment]
I think API was down, during that time. Can you please retry.

**Comment by msghera** [comment]
you shouldn't pass {Bangladesh}, pass is as Bangladesh 
```
python corona_data.py Bangladesh
```

**Comment by sunjid-rahman** [comment]
Thanks for help me out.
